# Revu Configuration File

# Coding guidelines for code reviews
codingGuidelines:
  - "Naming: Use semantically significant names for functions, classes, and parameters."
  - "Comments: Add comments only for complex code; simple code should be self-explanatory if clean code principles are followed."
  - "Documentation: Public functions must have concise docstrings explaining purpose and return values."
