#!/usr/bin/env sh
# Husky pre-commit hook
set -e

# Lint staged files and fix where possible
yarn lint-staged

# Run a full project typecheck to catch missing identifiers and other TS errors
yarn typecheck
